file(READ "${INPUT}" source)
string(REPLACE "unsigned short* ptr2 = buffer" "unsigned short* ptr2 = (unsigned short*)buffer" source "${source}")
string(REPLACE "__declspec(dllexport) int luaopen_luaoutbreaktracker" "extern \"C\" __declspec(dllexport) int luaopen_luaoutbreaktracker" source "${source}")
string(REPLACE "if (RItems->RItem[j].ID == 0x00||\n\t\t\t\tRItems->RItem[j].Count == 0xFFFF||\n\t\t\t\tRItems->RItem[j].EN != 0xFFFF||\n\t\t\t\t//RItems->RItem[j].Pick > 0 && RItems->RItem[j].Present ==0||\n\t\t\t\tRItems->RItem[j].Mix == 0x20)" "if (RItems->RItem[j].ID == 0x00 ||\n\t\t\t\tRItems->RItem[j].ID > 0xFF ||\n\t\t\t\tItems[RItems->RItem[j].ID - 1].RoomID != Players[0].RoomID)" source "${source}")
string(REPLACE "UpdatePickups();" "static unsigned int pickupUpdateCounter = 0;\n\tif ((pickupUpdateCounter++ % 6) == 0) UpdatePickups();" source "${source}")
string(REPLACE "UpdateEnemyList();" "static unsigned int enemyListUpdateCounter = 0;\n\tif ((enemyListUpdateCounter++ % 15) == 0) UpdateEnemyList();" source "${source}")
string(REPLACE "UpdateRoomMasters();" "static unsigned int roomMasterUpdateCounter = 0;\n\tif ((roomMasterUpdateCounter++ % 30) == 0) UpdateRoomMasters();" source "${source}")
file(WRITE "${OUTPUT}" "${source}")
